name: Build, Test, and Install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-install:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25'
        
    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
      
    - name: Build project
      run: cmake --build build --config Release
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.2
      
    - name: List build output (for debugging)
      run: |
        echo "Contents of build directory:"
        dir build /s /b *.dll
        echo "Contents of tests directory (if exists):"
        if (Test-Path tests) { dir tests /s /b *.dll } else { echo "tests directory not found" }
      
    - name: Run MS Tests
      run: |
        $testDlls = Get-ChildItem -Path "build" -Recurse -Filter "*.dll" | Where-Object { $_.Name -match "test" -or $_.Directory.Name -match "test" }
        if ($testDlls.Count -eq 0) {
          echo "No test DLLs found"
          exit 1
        }
        $testPaths = $testDlls | ForEach-Object { $_.FullName }
        echo "Found test DLLs: $($testPaths -join ', ')"
        vstest.console.exe $testPaths --logger:trx --resultsDirectory:TestResults
      continue-on-error: false
      
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: MS Test Results
        path: TestResults/*.trx
        reporter: dotnet-trx
        
    - name: Install project
      run: cmake --install build --prefix install --config Release
      
    - name: Upload installation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nudge-library-${{ github.sha }}
        path: install/
        retention-days: 30
        
    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ github.sha }}
        path: TestResults/
        retention-days: 7